# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.model import Model  # noqa: F401,E501
from swagger_server import util


class Node(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, model: Model=None):  # noqa: E501
        """Node - a model defined in Swagger

        :param name: The name of this Node.  # noqa: E501
        :type name: str
        :param model: The model of this Node.  # noqa: E501
        :type model: Model
        """
        self.swagger_types = {
            'name': str,
            'model': Model
        }

        self.attribute_map = {
            'name': 'name',
            'model': 'model'
        }

        self._name = name
        self._model = model

    @classmethod
    def from_dict(cls, dikt) -> 'Node':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Node of this Node.  # noqa: E501
        :rtype: Node
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Node.


        :return: The name of this Node.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Node.


        :param name: The name of this Node.
        :type name: str
        """

        self._name = name

    @property
    def model(self) -> Model:
        """Gets the model of this Node.


        :return: The model of this Node.
        :rtype: Model
        """
        return self._model

    @model.setter
    def model(self, model: Model):
        """Sets the model of this Node.


        :param model: The model of this Node.
        :type model: Model
        """

        self._model = model
