# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.legacy_model import LegacyModel  # noqa: F401,E501
from swagger_server import util


class Simulation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, models: List[LegacyModel]=None, namespace: str=None):  # noqa: E501
        """Simulation - a model defined in Swagger

        :param models: The models of this Simulation.  # noqa: E501
        :type models: List[LegacyModel]
        :param namespace: The namespace of this Simulation.  # noqa: E501
        :type namespace: str
        """
        self.swagger_types = {
            'models': List[LegacyModel],
            'namespace': str
        }

        self.attribute_map = {
            'models': 'models',
            'namespace': 'namespace'
        }

        self._models = models
        self._namespace = namespace

    @classmethod
    def from_dict(cls, dikt) -> 'Simulation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Simulation of this Simulation.  # noqa: E501
        :rtype: Simulation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def models(self) -> List[LegacyModel]:
        """Gets the models of this Simulation.


        :return: The models of this Simulation.
        :rtype: List[LegacyModel]
        """
        return self._models

    @models.setter
    def models(self, models: List[LegacyModel]):
        """Sets the models of this Simulation.


        :param models: The models of this Simulation.
        :type models: List[LegacyModel]
        """

        self._models = models

    @property
    def namespace(self) -> str:
        """Gets the namespace of this Simulation.


        :return: The namespace of this Simulation.
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace: str):
        """Sets the namespace of this Simulation.


        :param namespace: The namespace of this Simulation.
        :type namespace: str
        """

        self._namespace = namespace
