# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Simulation(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, models: List[str]=None, namespace: str=None):
        """
        Simulation - a model defined in Swagger

        :param models: The models of this Simulation.
        :type models: List[str]
        :param namespace: The namespace of this Simulation.
        :type namespace: str
        """
        self.swagger_types = {
            'models': List[str],
            'namespace': str
        }

        self.attribute_map = {
            'models': 'models',
            'namespace': 'namespace'
        }

        self._models = models
        self._namespace = namespace

    @classmethod
    def from_dict(cls, dikt) -> 'Simulation':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Simulation of this Simulation.
        :rtype: Simulation
        """
        return deserialize_model(dikt, cls)

    @property
    def models(self) -> List[str]:
        """
        Gets the models of this Simulation.
        The models that should run during this simulation

        :return: The models of this Simulation.
        :rtype: List[str]
        """
        return self._models

    @models.setter
    def models(self, models: List[str]):
        """
        Sets the models of this Simulation.
        The models that should run during this simulation

        :param models: The models of this Simulation.
        :type models: List[str]
        """

        self._models = models

    @property
    def namespace(self) -> str:
        """
        Gets the namespace of this Simulation.
        The unique namespace in which to run this simulation

        :return: The namespace of this Simulation.
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace: str):
        """
        Sets the namespace of this Simulation.
        The unique namespace in which to run this simulation

        :param namespace: The namespace of this Simulation.
        :type namespace: str
        """

        self._namespace = namespace