# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Yaml(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, yaml: str=None):  # noqa: E501
        """Yaml - a model defined in Swagger

        :param yaml: The yaml of this Yaml.  # noqa: E501
        :type yaml: str
        """
        self.swagger_types = {
            'yaml': str
        }

        self.attribute_map = {
            'yaml': 'yaml'
        }

        self._yaml = yaml

    @classmethod
    def from_dict(cls, dikt) -> 'Yaml':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The yaml of this Yaml.  # noqa: E501
        :rtype: Yaml
        """
        return util.deserialize_model(dikt, cls)

    @property
    def yaml(self) -> str:
        """Gets the yaml of this Yaml.


        :return: The yaml of this Yaml.
        :rtype: str
        """
        return self._yaml

    @yaml.setter
    def yaml(self, yaml: str):
        """Sets the yaml of this Yaml.


        :param yaml: The yaml of this Yaml.
        :type yaml: str
        """

        self._yaml = yaml
